<template>
	<px-auto-complete
		placeholder="Please input"
		v-model="input"
		:options="options"
		virtual-scroll
	></px-auto-complete>
</template>
<script setup lang="ts">
import { ref } from 'vue'

const input = ref('')

const data = [
	'pear',
	'plum',
	'cherry',
	'blueberry',
	'raspberry',
	'blackberry',
	'lemon',
	'lime',
	'pomegranate',
	'apricot',
	'apple',
	'banana',
	'orange',
	'grape',
	'strawberry',
	'mango',
	'pineapple',
	'peach',
	'kiwi',
	'watermelon',
	'grapefruit',
	'tangerine',
	'mandarin',
	'nectarine',
	'fig',
	'date',
	'olive',
	'coconut',
	'avocado',
	'papaya',
	'guava',
	'passion fruit',
	'lychee',
	'longan',
	'dragon fruit',
	'durian',
	'rambutan',
	'star fruit',
	'persimmon',
	'cantaloupe',
	'honeydew',
	'mulberry',
	'gooseberry',
	'currant',
	'elderberry',
	'cranberry',
	'boysenberry',
	'loganberry',
	'cloudberry',
	'salmonberry',
	'lingonberry',
	'bilberry',
	'huckleberry',
	'acai berry',
	'goji berry',
	'maqui berry',
	'camu camu',
	'cupuacu',
	'mamey',
	'sapodilla',
	'soursop',
	'guanabana',
	'jackfruit',
	'durian',
	'lychee',
	'longan',
	'rambutan',
	'pulasan',
	'mangosteen',
	'star apple',
	'rose apple',
	'wax apple',
	'java plum',
	'black plum',
	'white sapote',
	'black sapote',
	'marmalade plum',
	'pepino',
	'tamarillo',
	'cape gooseberry',
	'ground cherry',
	'physalis',
	'naranjilla',
	'lulo',
	'tomato',
	'potato',
	'carrot',
	'onion',
	'garlic',
	'cucumber',
	'bell pepper',
	'spinach',
	'lettuce',
	'broccoli',
	'cauliflower',
	'green bean',
	'pea',
	'zucchini',
	'eggplant',
	'celery',
	'asparagus',
	'brussels sprout',
	'kale',
	'chard',
	'radish',
	'turnip',
	'parsnip',
	'sweet potato',
	'yam',
	'pumpkin',
	'squash',
	'artichoke',
	'leek',
	'shallot',
	'chive',
	'scallion',
	'rhubarb',
	'beet',
	'swiss chard',
	'collard green',
	'mustard green',
	'dandelion green',
	'endive',
	'escarole',
	'fennel',
	'bok choy',
	'napa cabbage',
	'green cabbage',
	'red cabbage',
	'purple cabbage',
	'watercress',
	'arugula',
	'mushroom',
	'okra',
	'sweet corn',
	'corn',
	'rhubarb',
	'kohlrabi',
	'rutabaga',
	'celtuce',
	'bamboo shoot',
	'heart of palm',
	'artichoke',
	'jerusalem artichoke',
	'sunchoke',
	'chayote',
	'pattypan squash',
	'butternut squash',
	'acorn squash',
	'spaghetti squash',
	'zucchini',
	'yellow squash',
	'crookneck squash',
	'eggplant',
	'aubergine',
	'tomato',
	'cherry tomato',
	'plum tomato',
	'beefsteak tomato',
	'roma tomato',
	'grape tomato',
	'heirloom tomato',
	'bell pepper',
	'red bell pepper',
	'green bell pepper',
	'yellow bell pepper',
	'orange bell pepper',
	'jalapeno',
	'habanero',
	'serrano',
	'cayenne pepper',
	'tabasco pepper',
	'poblano',
	'ancho',
	'chipotle',
	'fresno pepper',
	'banana pepper',
	'pepperoncini',
	'shishito pepper',
	'green bean',
	'string bean',
	'snap bean',
	'haricot vert',
	'lima bean',
	'butter bean',
	'fava bean',
	'broad bean',
	'black bean',
	'kidney bean',
	'pinto bean',
	'navy bean',
	'cannellini bean',
	'great northern bean',
	'adzuki bean',
	'mung bean',
	'soybean',
	'lentil',
	'red lentil',
	'green lentil',
	'brown lentil',
	'black lentil',
	'chickpea',
	'garbanzo bean',
	'pea',
	'green pea',
	'snow pea',
	'sugar snap pea',
	'split pea',
	'black-eyed pea',
	'cowpea',
	'okra',
	'okra pod',
	'spinach',
	'baby spinach',
	'flat-leaf spinach',
	'malabar spinach',
	'water spinach',
	'kale',
	'curly kale',
	'tuscan kale',
	'lacinato kale',
	'red kale',
	'kale rabe',
	'rapini',
	'collard greens',
	'mustard greens',
	'turnip greens',
	'dandelion greens',
	'chard',
	'swiss chard',
	'rainbow chard',
	'beet greens',
	'spinach beet',
	'endive',
	'curly endive',
	'frisée',
	'escarole',
	'radicchio',
	'arugula',
	'rocket',
	'watercress',
	'land cress',
	'nasturtium',
	'sorrel',
	'spinach',
	'lettuce',
	'iceberg lettuce',
	'romaine lettuce',
	'butterhead lettuce',
	'boston lettuce',
	'bibb lettuce',
	'leaf lettuce',
	'green leaf lettuce',
	'red leaf lettuce',
	'arugula',
	'mixed greens',
	'mesclun',
	'microgreens',
	'alfalfa sprouts',
	'bean sprouts',
	'mung bean sprouts',
	'radish sprouts',
	'broccoli sprouts',
	'sunflower sprouts',
	'onion',
	'yellow onion',
	'red onion',
	'white onion',
	'sweet onion',
	'vidalia onion',
	'walla walla onion',
	'shallot',
	'green onion',
	'scallion',
	'chive',
	'garlic',
	'garlic clove',
	' elephant garlic',
	'leek',
	'ramp',
	'wild leek',
	'garlic chive',
	'chives',
	'asparagus',
	'green asparagus',
	'white asparagus',
	'purple asparagus',
	'celery',
	'celery stalk',
	'celery root',
	'celeriac',
	'fennel',
	'fennel bulb',
	'fennel frond',
	'carrot',
	'orange carrot',
	'purple carrot',
	'yellow carrot',
	'white carrot',
	'baby carrot',
	'parsnip',
	'turnip',
	'rutabaga',
	'swede',
	'kohlrabi',
	'radish',
	'red radish',
	'daikon radish',
	'black radish',
	'watermelon radish',
	'horseradish',
	'wasabi',
	'beet',
	'red beet',
	'golden beet',
	'chioggia beet',
	'sugar beet',
	'sweet potato',
	'orange sweet potato',
	'purple sweet potato',
	'white sweet potato',
	'yam',
	'true yam',
	'potato',
	'russet potato',
	'yukon gold potato',
	'red potato',
	'white potato',
	'fingerling potato',
	'sweet potato',
	'taro',
	'eddoe',
	'malanga',
	'yucca',
	'cassava',
	'manioc',
	'jicama',
	' Jerusalem artichoke',
	'sunchoke',
	'ginger',
	'fresh ginger',
	'galangal',
	'turmeric',
	'horseradish',
	'bamboo shoot',
	'fresh bamboo shoot',
	'canned bamboo shoot',
	'heart of palm',
	'artichoke',
	'globe artichoke',
	'jerusalem artichoke',
	'asparagus',
	'broccoli',
	'broccoli crown',
	'broccoli floret',
	'broccoli stem',
	'cauliflower',
	'white cauliflower',
	'purple cauliflower',
	'green cauliflower',
	'romanesco broccoli',
	'brussels sprout',
	'baby brussels sprout',
	'kale',
	'cabbage',
	'green cabbage',
	'red cabbage',
	'purple cabbage',
	'savoy cabbage',
	'napa cabbage',
	'chinese cabbage',
	'bok choy',
	'pak choi',
	'baby bok choy',
	'tatsoi',
	'mizuna',
	'komatsuna',
	'mustard greens',
	'collard greens',
	'spinach',
	'chard',
	'mushroom',
	'white button mushroom',
	'cremini mushroom',
	'portobello mushroom',
	'shiitake mushroom',
	'oyster mushroom',
	'enoki mushroom',
	'beech mushroom',
	'shimeji mushroom',
	'maitake mushroom',
	'reishi mushroom',
	'cordyceps',
	'truffle',
	'black truffle',
	'white truffle',
	'morel',
	'chanterelle',
	'ceps',
	'porcini',
	'pumpkin',
	'pie pumpkin',
	'sugar pumpkin',
	'jack-o-lantern pumpkin',
	'squash',
	'butternut squash',
	'acorn squash',
	'spaghetti squash',
	'hubbard squash',
	'kabocha squash',
	'delicata squash',
	'pattypan squash',
	'crookneck squash',
	'yellow squash',
	'zucchini',
	'summer squash',
	'winter squash',
	'chayote',
	'mirliton',
	'tomatillo',
	'ground cherry',
	'cape gooseberry',
	'physalis',
	'eggplant',
	'aubergine',
	'chinese eggplant',
	'Japanese eggplant',
	'white eggplant',
	'grape eggplant',
	'okra',
	'ladyfinger',
	'corn',
	'sweet corn',
	'baby corn',
	'corn on the cob',
	'popcorn',
	'sweet potato',
	'yam',
	'taro',
	'water chestnut',
	'lotus root',
	'bamboo shoot',
	'heart of palm',
	'artichoke',
	'jerusalem artichoke',
	'sunchoke',
	'chayote',
	'pattypan squash',
	'butternut squash',
	'acorn squash',
	'spaghetti squash',
	'zucchini',
	'yellow squash',
	'crookneck squash',
	'eggplant',
	'aubergine',
	'tomato',
	'cherry tomato',
	'plum tomato',
	'beefsteak tomato',
	'roma tomato',
	'grape tomato',
	'heirloom tomato',
	'bell pepper',
	'red bell pepper',
	'green bell pepper',
	'yellow bell pepper',
	'orange bell pepper',
	'jalapeno',
	'habanero',
	'serrano',
	'cayenne pepper',
	'tabasco pepper',
	'poblano',
	'ancho',
	'chipotle',
	'fresno pepper',
	'banana pepper',
	'pepperoncini',
	'shishito pepper',
	'green bean',
	'string bean',
	'snap bean',
	'haricot vert',
	'lima bean',
	'butter bean',
	'fava bean',
	'broad bean',
	'black bean',
	'kidney bean',
	'pinto bean',
	'navy bean',
	'cannellini bean',
	'great northern bean',
	'adzuki bean',
	'mung bean',
	'soybean',
	'lentil',
	'red lentil',
	'green lentil',
	'brown lentil',
	'black lentil',
	'chickpea',
	'garbanzo bean',
	'pea',
	'green pea',
	'snow pea',
	'sugar snap pea',
	'split pea',
	'black-eyed pea',
	'cowpea',
	'okra',
	'okra pod',
	'spinach',
	'baby spinach',
	'flat-leaf spinach',
	'malabar spinach',
	'water spinach',
	'kale',
	'curly kale',
	'tuscan kale',
	'lacinato kale',
	'red kale',
	'kale rabe',
	'rapini',
	'collard greens',
	'mustard greens',
	'turnip greens',
	'dandelion greens',
	'chard',
	'swiss chard',
	'rainbow chard',
	'beet greens',
	'spinach beet',
	'endive',
	'curly endive',
	'frisée',
	'escarole',
	'radicchio',
	'arugula',
	'rocket',
	'watercress',
	'land cress',
	'nasturtium',
	'sorrel',
	'spinach',
	'lettuce',
	'iceberg lettuce',
	'romaine lettuce',
	'butterhead lettuce',
	'boston lettuce',
	'bibb lettuce',
	'leaf lettuce',
	'green leaf lettuce',
	'red leaf lettuce',
	'arugula',
	'mixed greens',
	'mesclun',
	'microgreens',
	'alfalfa sprouts',
	'bean sprouts',
	'mung bean sprouts',
	'radish sprouts',
	'broccoli sprouts',
	'sunflower sprouts',
	'onion',
	'yellow onion',
	'red onion',
	'white onion',
	'sweet onion',
	'vidalia onion',
	'walla walla onion',
	'shallot',
	'green onion',
	'scallion',
	'chive',
	'garlic',
	'garlic clove',
	'elephant garlic',
	'leek',
	'ramp',
	'wild leek',
	'garlic chive',
	'chives',
	'asparagus',
	'green asparagus',
	'white asparagus',
	'purple asparagus',
	'celery',
	'celery stalk',
	'celery root',
	'celeriac',
	'fennel',
	'fennel bulb',
	'fennel frond',
	'carrot',
	'orange carrot',
	'purple carrot',
	'yellow carrot',
	'white carrot',
	'baby carrot',
	'parsnip',
	'turnip',
	'rutabaga',
	'swede',
	'kohlrabi',
	'radish',
	'red radish',
	'daikon radish',
	'black radish',
	'watermelon radish',
	'horseradish',
	'wasabi',
	'beet',
	'red beet',
	'golden beet',
	'chioggia beet',
	'sugar beet',
	'sweet potato',
	'orange sweet potato',
	'purple sweet potato',
	'white sweet potato',
	'yam',
	'true yam',
	'potato',
	'russet potato',
	'yukon gold potato',
	'red potato',
	'white potato',
	'fingerling potato',
	'sweet potato',
	'taro',
	'eddoe',
	'malanga',
	'yucca',
	'cassava',
	'manioc',
	'jicama',
	'Jerusalem artichoke',
	'sunchoke',
	'ginger',
	'fresh ginger',
	'galangal',
	'turmeric',
	'horseradish',
	'bamboo shoot',
	'fresh bamboo shoot',
	'canned bamboo shoot',
	'heart of palm',
	'artichoke',
	'globe artichoke',
	'jerusalem artichoke',
	'asparagus',
	'broccoli',
	'broccoli crown',
	'broccoli floret',
	'broccoli stem',
	'cauliflower',
	'white cauliflower',
	'purple cauliflower',
	'green cauliflower',
	'romanesco broccoli',
	'brussels sprout',
	'baby brussels sprout',
	'kale',
	'cabbage',
	'green cabbage',
	'red cabbage',
	'purple cabbage',
	'savoy cabbage',
	'napa cabbage',
	'chinese cabbage',
	'bok choy',
	'pak choi',
	'baby bok choy',
	'tatsoi',
	'mizuna',
	'komatsuna',
	'mustard greens',
	'collard greens',
	'spinach',
	'chard',
	'mushroom',
	'white button mushroom',
	'cremini mushroom',
	'portobello mushroom',
	'shiitake mushroom',
	'oyster mushroom',
	'enoki mushroom',
	'beech mushroom',
	'shimeji mushroom',
	'maitake mushroom',
	'reishi mushroom',
	'cordyceps',
	'truffle',
	'black truffle',
	'white truffle',
	'morel',
	'chanterelle',
	'ceps',
	'porcini',
	'pumpkin',
	'pie pumpkin',
	'sugar pumpkin',
	'jack-o-lantern pumpkin',
	'squash',
	'butternut squash',
	'acorn squash',
	'spaghetti squash',
	'hubbard squash',
	'kabocha squash',
	'delicata squash',
	'pattypan squash',
	'crookneck squash',
	'yellow squash',
	'zucchini',
	'summer squash',
	'winter squash',
	'chayote',
	'mirliton',
	'tomatillo',
	'ground cherry',
	'cape gooseberry',
	'physalis',
	'starfruit',
	'carambola',
	'kiwifruit',
	'kiwi berry',
	'golden kiwi',
	'green kiwi',
	'persimmon',
	'fuyu persimmon',
	'hachiya persimmon',
	'date',
	'medjool date',
	'deglet noor date',
	'fig',
	'black fig',
	'green fig',
	'mission fig',
	'kadota fig',
	'olive',
	'green olive',
	'black olive',
	'kalamata olive',
	'gaeta olive',
	'coconut',
	'young coconut',
	'mature coconut',
	'coconut water',
	'coconut meat',
	'avocado',
	'hass avocado',
	' fuerte avocado',
	'zutano avocado',
	'pinkerton avocado',
	'papaya',
	'solo papaya',
	'maradol papaya',
	'guava',
	'strawberry guava',
	'common guava',
	'passion fruit',
	'purple passion fruit',
	'yellow passion fruit',
	'lychee',
	'litchi',
	'longan',
	'dragon eye',
	'dragon fruit',
	'red dragon fruit',
	'yellow dragon fruit',
	'durian',
	'rambutan',
	'pulasan',
	'star apple',
	'caimito',
	'rose apple',
	'jambu',
	'wax apple',
	'java plum',
	'jamun',
	'black plum',
	'white sapote',
	'black sapote',
	'chocolate pudding fruit',
	'marmalade plum',
	'pepino',
	'melon pear',
	'tamarillo',
	'tree tomato',
	'cape gooseberry',
	'ground cherry',
	'physalis',
	'naranjilla',
	'lulo',
	'uchuva',
	'aguaymanto',
	'rambutan',
	'longan',
	'lychee',
	'pulasan',
	'durian',
	'jackfruit',
	'breadfruit',
	'chempedak',
	'cempedak',
	'soursop',
	'guanabana',
	'graviola',
	'custard apple',
	'cherimoya',
	'atemoya',
	'sweetsop',
	'annon',
	'mamey sapote',
	'mamey',
	'sapodilla',
	'chico',
	'naseberry',
	'sapote',
	'yellow sapote',
	'canistel',
	'eggfruit',
	'lucuma',
	'pawpaw',
	'asimina',
	'pomegranate',
	'pommegranate',
	'quince',
	'loquat',
	'Japanese plum',
	'persimmon',
	'date plum',
	'sloe',
	'blackthorn',
	'serviceberry',
	'juneberry',
	'hawthorn berry',
	'rowan berry',
	'mountain ash',
	'elderberry',
	'black elderberry',
	'red elderberry',
	'aronia berry',
	'chokeberry',
	'blueberry',
	'highbush blueberry',
	'lowbush blueberry',
	'rabbiteye blueberry',
	'bilberry',
	'whortleberry',
	'huckleberry',
	'black huckleberry',
	'blue huckleberry',
	'lingonberry',
	'cowberry',
	'partridgeberry',
	'cranberry',
	'American cranberry',
	'European cranberry',
	'bearberry',
	'kinnikinnick',
	'strawberry',
	'garden strawberry',
	'alpine strawberry',
	'wild strawberry',
	'raspberry',
	'red raspberry',
	'black raspberry',
	'purple raspberry',
	'golden raspberry',
	'blackberry',
	'dewberry',
	'boysenberry',
	'loganberry',
	'tayberry',
	'marionberry',
	'olallieberry',
	'youngberry',
	'cloudberry',
	'bakeapple',
	'salmonberry',
	'thimbleberry',
	'wineberry',
	'mulberry',
	'black mulberry',
	'red mulberry',
	'white mulberry',
	'gooseberry',
	'green gooseberry',
	'red gooseberry',
	'golden gooseberry',
	'currant',
	'red currant',
	'black currant',
	'white currant',
	'pink currant',
	'goji berry',
	'wolfberry',
	'goji',
	'maqui berry',
	'camu camu',
	'acai berry',
	'acai',
	'cupuacu',
	'copuacu',
	'bacuri',
	'buriti',
	'pupunha',
	'jaca',
	'jackfruit',
	'mangaba',
	'murici',
	'pitanga',
	'surinam cherry',
	'pitaya',
	'dragon fruit',
	'prickly pear',
	'cactus fruit',
	'tuna',
	'sabra',
	'fig',
	'date',
	'olive',
	'grape',
	'green grape',
	'red grape',
	'purple grape',
	'black grape',
	'seedless grape',
	'concord grape',
	'thompson seedless',
	'crimson seedless',
	'muscat grape',
	'champagne grape',
	'raisin',
	'sultana',
	'currant',
	'dried currant',
	'apricot',
	'dried apricot',
	'peach',
	'nectarine',
	'plum',
	'prune',
	'dried plum',
	'cherry',
	'sweet cherry',
	'sour cherry',
	'tart cherry',
	'bing cherry',
	'rainier cherry',
	'cherry plum',
	'myrobalan',
	'pear',
	'bartlett pear',
	'bosc pear',
	'anjou pear',
	'comice pear',
	'seckel pear',
	'apple',
	'red apple',
	'green apple',
	'yellow apple',
	'honeycrisp apple',
	'fuji apple',
	'gala apple',
	'pink lady apple',
	'granny smith apple',
	'golden delicious apple',
	'red delicious apple',
	'mcintosh apple',
	'braeburn apple',
	'jazz apple',
	'envy apple',
	'cosmic crisp apple',
	'orange',
	'navel orange',
	'valencia orange',
	'blood orange',
	'tangerine',
	'mandarin',
	'clementine',
	'satsuma',
	'tangelo',
	'minneola',
	'ugli fruit',
	'grapefruit',
	'white grapefruit',
	'pink grapefruit',
	'red grapefruit',
	'pomelo',
	'shaddock',
	'lemon',
	'meyer lemon',
	'eureka lemon',
	'lisbon lemon',
	'lime',
	'key lime',
	'persian lime',
	'kaffir lime',
	'bergamot',
	'yuzu',
	'kumquat',
	'calamondin',
	'finger lime',
	'lemonade fruit',
	'rangpur',
	'mandarin lime',
	'pineapple',
	'smooth cayenne pineapple',
	'golden pineapple',
	'sugarloaf pineapple',
	'baby pineapple',
	'mango',
	'alphonso mango',
	'tommy atkins mango',
	'haden mango',
	'kent mango',
	'keitt mango',
	'ataulfo mango',
	'manila mango',
	'watermelon',
	'seedless watermelon',
	'yellow watermelon',
	'mini watermelon',
	'cantaloupe',
	'muskmelon',
	'charentais melon',
	'honeydew',
	'green honeydew',
	'orange honeydew',
	'crenshaw melon',
	'casaba melon',
	'canary melon',
	'galia melon',
	'melon',
	'winter melon',
	'wax gourd',
	'ash gourd',
	'bitter melon',
	'bitter gourd',
	' karela',
	'sponge gourd',
	'luffa',
	'ridge gourd',
	'snake gourd',
	'bottle gourd',
	'calabash',
	'zucchini',
	'yellow squash',
	'pumpkin',
	'squash',
	'chayote',
	'tomatillo',
	'eggplant'
]

const options = ref(data)
</script>

<style lang="css" scoped>
.px-auto-complete {
	width: 320px;
}
</style>
