export const DEFAULT_ADDITION_COL_WIDTH = 48
export const DEFAULT_ROW_KEY = 'key'

export const TABLE_SELECTION_COL_SYMBOL = Symbol('TABLE_SELECTION_COL_SYMBOL')
export const TABLE_EXPANDABLE_COL_SYMBOL = Symbol('TABLE_EXPANDABLE_COL_SYMBOL')
export const TABLE_EMPTY_COL_SYMBOL = Symbol('TABLE_EMPTY_COL_SYMBOL')
export const TABLE_SUMMARY_ROW_SYMBOL = Symbol('TABLE_SUMMARY_ROW_SYMBOL')

export const DEFAULT_WIDTH = 80
export const DEFAULT_MIN_WIDTH = 0
